services:
  Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\GetAgendaDayController:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\GetAgendaDayController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\GetAgendaUpcomingController:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\GetAgendaUpcomingController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\GetAgendaCalendarController:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\GetAgendaCalendarController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\CreateAgendaEntryController:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\CreateAgendaEntryController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\CreateAgendaEntrySeriesController:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\CreateAgendaEntrySeriesController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\GetAgendaEntrySeriesController:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\GetAgendaEntrySeriesController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\UpdateAgendaEntrySeriesController:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\UpdateAgendaEntrySeriesController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\DeleteAgendaEntrySeriesController:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\DeleteAgendaEntrySeriesController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\UpdateAgendaEntryController:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\UpdateAgendaEntryController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\ChangeAgendaEntryStatusController:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\ChangeAgendaEntryStatusController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\DeleteAgendaEntryController:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\Controller\DeleteAgendaEntryController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }
