services:
  Nutrition\Pantry\Inventory\Infrastructure\UI\Mcp\Tool\StartInventoryTool:
    class: Nutrition\Pantry\Inventory\Infrastructure\UI\Mcp\Tool\StartInventoryTool
    arguments:
      $messageBus: '@messenger.bus.default'
      $requestStack: '@request_stack'
    tags:
      - { name: 'mcp.tool' }

  Nutrition\Pantry\Inventory\Infrastructure\UI\Mcp\Tool\CountInventoryItemTool:
    class: Nutrition\Pantry\Inventory\Infrastructure\UI\Mcp\Tool\CountInventoryItemTool
    arguments:
      $messageBus: '@messenger.bus.default'
      $requestStack: '@request_stack'
    tags:
      - { name: 'mcp.tool' }

  Nutrition\Pantry\Inventory\Infrastructure\UI\Mcp\Tool\ValidateInventoryTool:
    class: Nutrition\Pantry\Inventory\Infrastructure\UI\Mcp\Tool\ValidateInventoryTool
    arguments:
      $messageBus: '@messenger.bus.default'
      $requestStack: '@request_stack'
    tags:
      - { name: 'mcp.tool' }
