get_diary_calendar:
  path: /api/v1/nutrition/diary/calendar
  methods: [GET]
  controller: Nutrition\Diary\Diary\Infrastructure\UI\API\Controller\GetDiaryCalendarController

get_diary:
  path: /api/v1/nutrition/diary
  methods: [GET]
  controller: Nutrition\Diary\Diary\Infrastructure\UI\API\Controller\GetDiaryController

create_diary_entry:
  path: /api/v1/nutrition/diary
  methods: [POST]
  controller: Nutrition\Diary\Diary\Infrastructure\UI\API\Controller\CreateDiaryEntryController

create_quick_diary_entry:
  path: /api/v1/nutrition/diary/quick
  methods: [POST]
  controller: Nutrition\Diary\Diary\Infrastructure\UI\API\Controller\CreateQuickDiaryEntryController

update_quick_diary_entry:
  path: /api/v1/nutrition/diary/{diaryEntryId}/quick
  methods: [PUT]
  controller: Nutrition\Diary\Diary\Infrastructure\UI\API\Controller\UpdateQuickDiaryEntryController
  requirements:
    diaryEntryId: '[0-9a-fA-F-]{36}'

update_diary_entry:
  path: /api/v1/nutrition/diary/{diaryEntryId}
  methods: [PUT]
  controller: Nutrition\Diary\Diary\Infrastructure\UI\API\Controller\UpdateDiaryEntryController
  requirements:
    diaryEntryId: '[0-9a-fA-F-]{36}'

delete_diary_entry:
  path: /api/v1/nutrition/diary/{diaryEntryId}
  methods: [DELETE]
  controller: Nutrition\Diary\Diary\Infrastructure\UI\API\Controller\DeleteDiaryEntryController
  requirements:
    diaryEntryId: '[0-9a-fA-F-]{36}'
