export enum FinanceCategory {
  GROCERIES = "groceries",
  RESTAURANTS = "restaurants",
  GYM = "gym",
  TRANSPORT = "transport",
  LEISURE = "leisure",
  HOME = "home",
  BILLS = "bills",
  HEALTH = "health",
  BEAUTY = "beauty",
  CLOTHING = "clothing",
  TREATS = "treats",
  GIFTS = "gifts",
  TRAVEL = "travel",
  PETS = "pets",
  SUBSCRIPTIONS = "subscriptions",
  INVESTMENTS = "investments",
  OTHER = "other",
}
