services:
  Nutrition\Diary\Diary\Infrastructure\Domain\Service\DiaryWriterRecipeNutritionGraphProvider:
    class: Nutrition\Recipe\Recipe\Infrastructure\Domain\QueryModel\Doctrine\DoctrineRecipeNutritionGraphProvider
    arguments:
      $connection: '@doctrine.dbal.writer_tenant_connection'

  Nutrition\Diary\Diary\Domain\Service\DiaryEntrySnapshotCalculator:
    class: Nutrition\Diary\Diary\Infrastructure\Domain\Service\RecipeGraphDiaryEntrySnapshotCalculator
    arguments:
      $graphProvider: '@Nutrition\Diary\Diary\Infrastructure\Domain\Service\DiaryWriterRecipeNutritionGraphProvider'
      $calculator: '@Nutrition\Recipe\Recipe\Domain\Service\RecipeNutritionCalculator'

  Nutrition\Diary\Diary\Domain\Service\DiaryEntryTreeBuilder:
    class: Nutrition\Diary\Diary\Infrastructure\Domain\Service\RecipeGraphDiaryEntryTreeBuilder
    arguments:
      $graphProvider: '@Nutrition\Diary\Diary\Infrastructure\Domain\Service\DiaryWriterRecipeNutritionGraphProvider'
      $calculator: '@Nutrition\Recipe\Recipe\Domain\Service\RecipeBreakdownCalculator'
      $lotCompositionProvider: '@Nutrition\Diary\Diary\Domain\Service\DiaryLotCompositionProvider'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'

  Nutrition\Diary\Diary\Domain\Service\DiaryLotCompositionProvider:
    class: Nutrition\Diary\Diary\Infrastructure\Domain\Service\DoctrineDiaryLotCompositionProvider
    arguments:
      $connection: '@doctrine.dbal.writer_tenant_connection'

  Nutrition\Diary\Diary\Domain\Service\DiaryArticleNeedsCalculator:
    class: Nutrition\Diary\Diary\Domain\Service\DiaryArticleNeedsCalculator
