services:
  Authorization\User\PushSubscription\Domain\QueryModel\GetPushNotificationsConfigNeedleDataQuery:
    class: Authorization\User\PushSubscription\Infrastructure\Domain\QueryModel\Doctrine\DoctrineGetPushNotificationsConfigNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.master_connection'
