services:
  Nutrition\Pantry\Location\Infrastructure\UI\API\Controller\GetLocationsController:
    class: Nutrition\Pantry\Location\Infrastructure\UI\API\Controller\GetLocationsController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Pantry\Location\Infrastructure\UI\API\Controller\GetLocationController:
    class: Nutrition\Pantry\Location\Infrastructure\UI\API\Controller\GetLocationController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Pantry\Location\Infrastructure\UI\API\Controller\CreateLocationController:
    class: Nutrition\Pantry\Location\Infrastructure\UI\API\Controller\CreateLocationController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Pantry\Location\Infrastructure\UI\API\Controller\UpdateLocationController:
    class: Nutrition\Pantry\Location\Infrastructure\UI\API\Controller\UpdateLocationController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Pantry\Location\Infrastructure\UI\API\Controller\DeleteLocationController:
    class: Nutrition\Pantry\Location\Infrastructure\UI\API\Controller\DeleteLocationController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }
