doctrine:
    dbal:
        default_connection: master
        connections:
            master:
                driver: pdo_mysql
                host: '%env(resolve:DATABASE_MASTER_HOST)%'
                port: '%env(resolve:DATABASE_MASTER_PORT)%'
                dbname: '%env(resolve:DATABASE_MASTER_NAME)%'
                user: '%env(resolve:DATABASE_MASTER_USER)%'
                password: '%env(resolve:DATABASE_MASTER_PASSWORD)%'
                charset: utf8mb4
                server_version: '%env(resolve:DATABASE_MASTER_SERVER_VERSION)%'
            writer_tenant:
                url: '%env(resolve:DATABASE_WRITER_TENANT_TEMPLATE_URL)%'
                charset: utf8mb4
            reader_tenant:
                url: '%env(resolve:DATABASE_READER_TENANT_TEMPLATE_URL)%'
                charset: utf8mb4
    orm:
        default_entity_manager: master_manager
        enable_native_lazy_objects: true
        entity_managers:
            master_manager:
                connection: master
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    User:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Authorization/User/User/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Authorization\User\User\Domain\Model'
                        alias: user
                    PasswordResetToken:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Authorization/User/PasswordResetToken/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Authorization\User\PasswordResetToken\Domain\Model'
                        alias: password_reset_token
                    RefreshToken:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Authorization/User/RefreshToken/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Authorization\User\RefreshToken\Domain\Model'
                        alias: refresh_token
                    EmailVerificationToken:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Authorization/User/EmailVerificationToken/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Authorization\User\EmailVerificationToken\Domain\Model'
                        alias: email_verification_token
                    GlobalArticle:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Nutrition/GlobalCatalog/Article/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Nutrition\GlobalCatalog\Article\Domain\Model'
                        alias: global_article
            tenant_manager:
                connection: writer_tenant
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false
                mappings:
                    DomainEventLog:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Shared/Shared/DomainEventLog/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Shared\Shared\DomainEventLog\Domain\Model'
                        alias: domain_event_log
                    Article:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Nutrition/Catalog/Article/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Nutrition\Catalog\Article\Domain\Model'
                        alias: article
                    NutritionFacts:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Nutrition/Catalog/NutritionFacts/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Nutrition\Catalog\NutritionFacts\Domain\Model'
                        alias: nutrition_facts
                    Supermarket:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Nutrition/Catalog/Supermarket/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Nutrition\Catalog\Supermarket\Domain\Model'
                        alias: supermarket
                    Category:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Nutrition/Catalog/Category/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Nutrition\Catalog\Category\Domain\Model'
                        alias: category
                    Recipe:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Nutrition/Recipe/Recipe/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Nutrition\Recipe\Recipe\Domain\Model'
                        alias: recipe
                    DiaryEntry:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Nutrition/Diary/Diary/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Nutrition\Diary\Diary\Domain\Model'
                        alias: diary_entry
                    Exercise:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Gym/Library/Exercise/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Gym\Library\Exercise\Domain\Model'
                        alias: exercise
                    Session:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Gym/Training/Session/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Gym\Training\Session\Domain\Model'
                        alias: session
                    Workout:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Gym/Training/Workout/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Gym\Training\Workout\Domain\Model'
                        alias: workout
                    DiaryGoal:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Nutrition/Diary/Goal/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Nutrition\Diary\Goal\Domain\Model'
                        alias: diary_goal
                    ShoppingListItem:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Nutrition/Shopping/Shopping/Infrastructure/Domain/Model/Doctrine/Mapping'
                        prefix: 'Nutrition\Shopping\Shopping\Domain\Model'
                        alias: shopping_list_item