parameters:
    mcp.resources:
        article:
            class: 'Nutrition\Catalog\Article\Domain\Model\Article'
            sidecar: '%kernel.project_dir%/src/Nutrition/Catalog/Article/Infrastructure/Domain/Model/Doctrine/Mapping/Article.mcp.yaml'
            read_roles: [ROLE_GOD, ROLE_USER]
            write_roles: [ROLE_GOD, ROLE_USER]

        nutrition_facts:
            class: 'Nutrition\Catalog\NutritionFacts\Domain\Model\NutritionFacts'
            sidecar: '%kernel.project_dir%/src/Nutrition/Catalog/NutritionFacts/Infrastructure/Domain/Model/Doctrine/Mapping/NutritionFacts.mcp.yaml'
            read_roles: [ROLE_GOD, ROLE_USER]
            write_roles: [ROLE_GOD, ROLE_USER]

        supermarket:
            class: 'Nutrition\Catalog\Supermarket\Domain\Model\Supermarket'
            sidecar: '%kernel.project_dir%/src/Nutrition/Catalog/Supermarket/Infrastructure/Domain/Model/Doctrine/Mapping/Supermarket.mcp.yaml'
            read_roles: [ROLE_GOD, ROLE_USER]
            write_roles: [ROLE_GOD, ROLE_USER]

        category:
            class: 'Nutrition\Catalog\Category\Domain\Model\Category'
            sidecar: '%kernel.project_dir%/src/Nutrition/Catalog/Category/Infrastructure/Domain/Model/Doctrine/Mapping/Category.mcp.yaml'
            read_roles: [ROLE_GOD, ROLE_USER]
            write_roles: [ROLE_GOD, ROLE_USER]

        exercise:
            class: 'Gym\Library\Exercise\Domain\Model\Exercise'
            sidecar: '%kernel.project_dir%/src/Gym/Library/Exercise/Infrastructure/Domain/Model/Doctrine/Mapping/Exercise.mcp.yaml'
            read_roles: [ROLE_GOD, ROLE_USER]
            write_roles: [ROLE_GOD, ROLE_USER]

        training_session:
            class: 'Gym\Training\Session\Domain\Model\Session'
            sidecar: '%kernel.project_dir%/src/Gym/Training/Session/Infrastructure/Domain/Model/Doctrine/Mapping/Session.mcp.yaml'
            read_roles: [ROLE_GOD, ROLE_USER]
            write_roles: [ROLE_GOD, ROLE_USER]

        session_exercise:
            class: 'Gym\Training\Session\Domain\Model\SessionExercise'
            sidecar: '%kernel.project_dir%/src/Gym/Training/Session/Infrastructure/Domain/Model/Doctrine/Mapping/SessionExercise.mcp.yaml'
            read_roles: [ROLE_GOD, ROLE_USER]
            write_roles: [ROLE_GOD, ROLE_USER]

        exercise_set:
            class: 'Gym\Training\Session\Domain\Model\ExerciseSet'
            sidecar: '%kernel.project_dir%/src/Gym/Training/Session/Infrastructure/Domain/Model/Doctrine/Mapping/ExerciseSet.mcp.yaml'
            read_roles: [ROLE_GOD, ROLE_USER]
            write_roles: [ROLE_GOD, ROLE_USER]
