label: Supermarket

fields:
  name:
    writable: true
    required: true
    min: 2
    max: 255
    unique: true
    filterable: true
    sortable: true

relations: {}

cascade_delete:
  - { resource: supermarket_aisle, foreign_field: supermarketId }
