services:
  Nutrition\Catalog\Supermarket\Infrastructure\UI\API\Controller\GetSupermarketsController:
    class: Nutrition\Catalog\Supermarket\Infrastructure\UI\API\Controller\GetSupermarketsController
    arguments:
      $messageBus: '@messenger.bus.default'
      $logger: '@logger'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Catalog\Supermarket\Infrastructure\UI\API\Controller\GetSupermarketController:
    class: Nutrition\Catalog\Supermarket\Infrastructure\UI\API\Controller\GetSupermarketController
    arguments:
      $messageBus: '@messenger.bus.default'
      $logger: '@logger'
    tags:
      - { name: controller.service_arguments }
