services:
  Shared\Tool\Tool\Infrastructure\UI\API\Controller\CspReportController:
    class: Shared\Tool\Tool\Infrastructure\UI\API\Controller\CspReportController
    arguments:
      $logger: '@monolog.logger.csp'
      $cspReportLimiter: '@limiter.csp_report'
    tags:
      - { name: controller.service_arguments }

  Shared\Tool\Tool\Infrastructure\UI\API\Controller\UploadImageController:
    class: Shared\Tool\Tool\Infrastructure\UI\API\Controller\UploadImageController
    arguments:
      $imageStorageService: '@Shared\Tool\Tool\Domain\Service\ImageStorageService'
    tags:
      - { name: controller.service_arguments }
