services:
  Economy\Finance\Recurrence\Domain\Model\FinanceRecurrenceRepository:
    class: Economy\Finance\Recurrence\Infrastructure\Domain\Model\Doctrine\DoctrineFinanceRecurrenceRepository
    factory: ["@doctrine.orm.tenant_manager_entity_manager", getRepository]
    arguments:
      - Economy\Finance\Recurrence\Domain\Model\FinanceRecurrence
