apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-ops
    receivers:
      - uid: email-ops
        type: email
        settings:
          addresses: $GRAFANA_ALERT_EMAIL
          singleEmail: true
