services:
  Nutrition\Pantry\Movement\Domain\Service\StockMovementUnitConverter:
    class: Nutrition\Pantry\Movement\Infrastructure\Domain\Service\Doctrine\DoctrineStockMovementUnitConverter
    arguments:
      $connection: '@doctrine.dbal.writer_tenant_connection'

  Nutrition\Pantry\Movement\Domain\Service\StockLedger:
    class: Nutrition\Pantry\Movement\Infrastructure\Domain\Service\Doctrine\DoctrineStockLedger
    arguments:
      $connection: '@doctrine.dbal.writer_tenant_connection'
