services:
  Nutrition\Pantry\Movement\Domain\Service\StockBalanceCalculator:
    class: Nutrition\Pantry\Movement\Infrastructure\Domain\Service\Doctrine\DoctrineStockBalanceCalculator
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'

  Nutrition\Pantry\Movement\Domain\Service\StockMovementUnitConverter:
    class: Nutrition\Pantry\Movement\Infrastructure\Domain\Service\Doctrine\DoctrineStockMovementUnitConverter
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'
