services:
  Nutrition\Kitchen\Production\Application\Command\StartProductionCommandHandler:
    class: Nutrition\Kitchen\Production\Application\Command\StartProductionCommandHandler
    arguments:
      $productionRepository: '@Nutrition\Kitchen\Production\Domain\Model\ProductionRepository'
      $needleDataQuery: '@Nutrition\Kitchen\Production\Domain\QueryModel\StartProductionNeedleDataQuery'
      $domainEventCollectorService: '@Shared\Shared\Shared\Domain\Service\DomainEventCollectorService'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Nutrition\Kitchen\Production\Application\Command\FinishProductionCommandHandler:
    class: Nutrition\Kitchen\Production\Application\Command\FinishProductionCommandHandler
    arguments:
      $productionRepository: '@Nutrition\Kitchen\Production\Domain\Model\ProductionRepository'
      $needleDataQuery: '@Nutrition\Kitchen\Production\Domain\QueryModel\FinishProductionNeedleDataQuery'
      $domainEventCollectorService: '@Shared\Shared\Shared\Domain\Service\DomainEventCollectorService'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Nutrition\Kitchen\Production\Application\Command\DiscardProductionCommandHandler:
    class: Nutrition\Kitchen\Production\Application\Command\DiscardProductionCommandHandler
    arguments:
      $productionRepository: '@Nutrition\Kitchen\Production\Domain\Model\ProductionRepository'
      $domainEventCollectorService: '@Shared\Shared\Shared\Domain\Service\DomainEventCollectorService'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
