services:
  Nutrition\Kitchen\Production\Application\Query\GetProductionQueryHandler:
    class: Nutrition\Kitchen\Production\Application\Query\GetProductionQueryHandler
    arguments:
      $needleDataQuery: '@Nutrition\Kitchen\Production\Domain\QueryModel\GetProductionNeedleDataQuery'
      $dataTransform: '@Nutrition\Kitchen\Production\Application\Query\GetProductionDataTransform'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Nutrition\Kitchen\Production\Application\Query\GetProductionDataTransform:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\DataTransform\ApiGetProductionDataTransform

  Nutrition\Kitchen\Production\Application\Query\GetProductionsQueryHandler:
    class: Nutrition\Kitchen\Production\Application\Query\GetProductionsQueryHandler
    arguments:
      $needleDataQuery: '@Nutrition\Kitchen\Production\Domain\QueryModel\GetProductionsNeedleDataQuery'
      $dataTransform: '@Nutrition\Kitchen\Production\Application\Query\GetProductionsDataTransform'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Nutrition\Kitchen\Production\Application\Query\GetProductionsDataTransform:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\DataTransform\ApiGetProductionsDataTransform

  Nutrition\Kitchen\Production\Application\Query\GetProductionProposalQueryHandler:
    class: Nutrition\Kitchen\Production\Application\Query\GetProductionProposalQueryHandler
    arguments:
      $needleDataQuery: '@Nutrition\Kitchen\Production\Domain\QueryModel\GetProductionProposalNeedleDataQuery'
      $dataTransform: '@Nutrition\Kitchen\Production\Application\Query\GetProductionProposalDataTransform'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Nutrition\Kitchen\Production\Application\Query\GetProductionProposalDataTransform:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\DataTransform\ApiGetProductionProposalDataTransform

  Nutrition\Kitchen\Production\Application\Query\GetProductionItemQueryHandler:
    class: Nutrition\Kitchen\Production\Application\Query\GetProductionItemQueryHandler
    arguments:
      $needleDataQuery: '@Nutrition\Kitchen\Production\Domain\QueryModel\GetProductionItemNeedleDataQuery'
      $dataTransform: '@Nutrition\Kitchen\Production\Application\Query\GetProductionItemDataTransform'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Nutrition\Kitchen\Production\Application\Query\GetProductionItemDataTransform:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\DataTransform\ApiGetProductionItemDataTransform
