services:
  Nutrition\Pantry\RecipeStock\Application\Subscriber\DeleteRecipeStockOnRecipeDeleted:
    class: Nutrition\Pantry\RecipeStock\Application\Subscriber\DeleteRecipeStockOnRecipeDeleted
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: 'domain_event_subscriber', event: 'golifecraft.nutrition.event.1.recipe.deleted' }

  Nutrition\Pantry\RecipeStock\Application\Subscriber\UpdateRecipeStockOnProductionItemCookChanged:
    class: Nutrition\Pantry\RecipeStock\Application\Subscriber\UpdateRecipeStockOnProductionItemCookChanged
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: 'domain_event_subscriber', event: 'golifecraft.nutrition.event.1.production.item_cooked' }
      - { name: 'domain_event_subscriber', event: 'golifecraft.nutrition.event.1.production.item_uncooked' }

  Nutrition\Pantry\RecipeStock\Application\Subscriber\UpdateSubRecipeStockOnProductionItemCookChanged:
    class: Nutrition\Pantry\RecipeStock\Application\Subscriber\UpdateSubRecipeStockOnProductionItemCookChanged
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: 'domain_event_subscriber', event: 'golifecraft.nutrition.event.1.production.item_cooked' }
      - { name: 'domain_event_subscriber', event: 'golifecraft.nutrition.event.1.production.item_uncooked' }

  Nutrition\Pantry\RecipeStock\Application\Subscriber\UpdateRecipeStockOnDiaryEntryConsumed:
    class: Nutrition\Pantry\RecipeStock\Application\Subscriber\UpdateRecipeStockOnDiaryEntryConsumed
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: 'domain_event_subscriber', event: 'golifecraft.nutrition.event.1.diary_entry.consumed' }

  Nutrition\Pantry\RecipeStock\Application\Subscriber\ClearRecipeStockLocationOnLocationDeleted:
    class: Nutrition\Pantry\RecipeStock\Application\Subscriber\ClearRecipeStockLocationOnLocationDeleted
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: 'domain_event_subscriber', event: 'golifecraft.nutrition.event.1.pantry_location.deleted' }

  Nutrition\Pantry\RecipeStock\Application\Subscriber\UpdateRecipeStockOnInventoryValidated:
    class: Nutrition\Pantry\RecipeStock\Application\Subscriber\UpdateRecipeStockOnInventoryValidated
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: 'domain_event_subscriber', event: 'golifecraft.nutrition.event.1.inventory.validated' }
