services:
  Nutrition\GlobalCatalog\Article\Domain\QueryModel\GetGlobalArticlesNeedleDataQuery:
    class: Nutrition\GlobalCatalog\Article\Infrastructure\Domain\QueryModel\Doctrine\DoctrineGetGlobalArticlesNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.master_connection'

  Nutrition\GlobalCatalog\Article\Domain\QueryModel\GetGlobalArticleFacetsNeedleDataQuery:
    class: Nutrition\GlobalCatalog\Article\Infrastructure\Domain\QueryModel\Doctrine\DoctrineGetGlobalArticleFacetsNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.master_connection'

  Nutrition\GlobalCatalog\Article\Domain\QueryModel\GetGlobalArticleNeedleDataQuery:
    class: Nutrition\GlobalCatalog\Article\Infrastructure\Domain\QueryModel\Doctrine\DoctrineGetGlobalArticleNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.master_connection'
