services:
  Agenda\Agenda\Agenda\Application\Query\GetAgendaDayQueryHandler:
    class: Agenda\Agenda\Agenda\Application\Query\GetAgendaDayQueryHandler
    arguments:
      $needleDataQuery: '@Agenda\Agenda\Agenda\Domain\QueryModel\GetAgendaDayNeedleDataQuery'
      $dataTransform: '@Agenda\Agenda\Agenda\Application\Query\GetAgendaDayDataTransform'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Agenda\Agenda\Agenda\Application\Query\GetAgendaDayDataTransform:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\DataTransform\ApiGetAgendaDayDataTransform

  Agenda\Agenda\Agenda\Application\Query\GetAgendaCalendarQueryHandler:
    class: Agenda\Agenda\Agenda\Application\Query\GetAgendaCalendarQueryHandler
    arguments:
      $needleDataQuery: '@Agenda\Agenda\Agenda\Domain\QueryModel\GetAgendaCalendarNeedleDataQuery'
      $dataTransform: '@Agenda\Agenda\Agenda\Application\Query\GetAgendaCalendarDataTransform'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Agenda\Agenda\Agenda\Application\Query\GetAgendaCalendarDataTransform:
    class: Agenda\Agenda\Agenda\Infrastructure\UI\API\DataTransform\ApiGetAgendaCalendarDataTransform
