services:
  Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\GetPushNotificationsConfigController:
    class: Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\GetPushNotificationsConfigController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\SubscribeToPushNotificationsController:
    class: Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\SubscribeToPushNotificationsController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\UnsubscribeFromPushNotificationsController:
    class: Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\UnsubscribeFromPushNotificationsController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\SendTestPushNotificationController:
    class: Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\SendTestPushNotificationController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }
