get_push_notifications_config:
  path: /api/v1/authorization/me/push-notifications
  methods: [GET]
  controller: Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\GetPushNotificationsConfigController

send_test_push_notification:
  path: /api/v1/authorization/me/push-notifications/test
  methods: [POST]
  controller: Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\SendTestPushNotificationController

subscribe_to_push_notifications:
  path: /api/v1/authorization/me/push-subscriptions
  methods: [PUT]
  controller: Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\SubscribeToPushNotificationsController

unsubscribe_from_push_notifications:
  path: /api/v1/authorization/me/push-subscriptions
  methods: [DELETE]
  controller: Authorization\User\PushSubscription\Infrastructure\UI\API\Controller\UnsubscribeFromPushNotificationsController
