services:
  Mcp\Server\Mcp\Domain\QueryModel\WriteModelNeedleDataQuery:
    class: Mcp\Server\Mcp\Infrastructure\Domain\QueryModel\Doctrine\DoctrineWriteModelNeedleDataQuery
    arguments:
      $entityManager: '@doctrine.orm.tenant_manager_entity_manager'
