services:
  Mcp\Server\Mcp\Domain\QueryModel\ModelExistsNeedleDataQuery:
    class: Mcp\Server\Mcp\Infrastructure\Domain\QueryModel\Doctrine\DoctrineModelExistsNeedleDataQuery
    arguments:
      $entityManager: '@doctrine.orm.tenant_manager_entity_manager'
