services:
  Shared\Tenant\Tenant\Domain\Service\TenantIdentifierGenerator:
    class: Shared\Tenant\Tenant\Infrastructure\Domain\Service\Doctrine\DoctrineTenantIdentifierGenerator
    arguments:
      $connection: '@doctrine.dbal.master_connection'

  Shared\Tenant\Tenant\Domain\Service\TenantProvisioner:
    class: Shared\Tenant\Tenant\Infrastructure\Domain\Service\Doctrine\DoctrineTenantProvisioner
    arguments:
      $tenantEntityManager: '@doctrine.orm.tenant_manager_entity_manager'
      $writerHost: '%env(DATABASE_TENANT_WRITER_HOST)%'
      $port: '%env(DATABASE_TENANT_PORT)%'
      $serverUsername: '%env(DATABASE_TENANT_USER)%'
      $serverPassword: '%env(DATABASE_TENANT_PASSWORD)%'

  Shared\Tenant\Tenant\Domain\Service\TenantConnectionSwitcher:
    class: Shared\Tenant\Tenant\Infrastructure\Domain\Service\Doctrine\DoctrineTenantConnectionSwitcher
    arguments:
      - '@doctrine.dbal.writer_tenant_connection'
      - '@doctrine.dbal.reader_tenant_connection'
      - '%env(DATABASE_TENANT_WRITER_HOST)%'
      - '%env(DATABASE_TENANT_READER_HOST)%'
      - '%env(DATABASE_TENANT_PORT)%'
      - '%env(DATABASE_TENANT_USER)%'
      - '%env(DATABASE_TENANT_PASSWORD)%'
