services:
  Nutrition\Menu\Menu\Domain\Service\MenuDocumentRenderer:
    class: Nutrition\Menu\Menu\Infrastructure\Domain\Service\Dompdf\DompdfMenuDocumentRenderer
    arguments:
      $twig: '@twig'
      $fontDirectory: '%kernel.project_dir%/assets/fonts'
      $cacheDirectory: '%kernel.cache_dir%/dompdf'

  Nutrition\Menu\Menu\Infrastructure\Domain\Service\MenuWriterRecipeNutritionGraphProvider:
    class: Nutrition\Recipe\Recipe\Infrastructure\Domain\QueryModel\Doctrine\DoctrineRecipeNutritionGraphProvider
    arguments:
      $connection: '@doctrine.dbal.writer_tenant_connection'

  Nutrition\Menu\Menu\Domain\Service\MenuItemTreeBuilder:
    class: Nutrition\Menu\Menu\Infrastructure\Domain\Service\RecipeGraphMenuItemTreeBuilder
    arguments:
      $graphProvider: '@Nutrition\Menu\Menu\Infrastructure\Domain\Service\MenuWriterRecipeNutritionGraphProvider'
      $calculator: '@Nutrition\Recipe\Recipe\Domain\Service\RecipeBreakdownCalculator'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
