services:
  Shared\Shared\DomainEventLog\Infrastructure\UI\API\Controller\GetDomainEventLogsController:
    class: Shared\Shared\DomainEventLog\Infrastructure\UI\API\Controller\GetDomainEventLogsController
    arguments:
      $messageBus: '@messenger.bus.default'
      $logger: '@logger'
    tags:
      - { name: controller.service_arguments }

  Shared\Shared\DomainEventLog\Infrastructure\UI\API\Controller\GetDomainEventLogController:
    class: Shared\Shared\DomainEventLog\Infrastructure\UI\API\Controller\GetDomainEventLogController
    arguments:
      $messageBus: '@messenger.bus.default'
      $logger: '@logger'
    tags:
      - { name: controller.service_arguments }
