services:
  Nutrition\Pantry\RecipeStock\Infrastructure\UI\API\Controller\UpdateRecipeStockController:
    class: Nutrition\Pantry\RecipeStock\Infrastructure\UI\API\Controller\UpdateRecipeStockController
    arguments:
      $messageBus: '@messenger.bus.default'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: controller.service_arguments }
