services:
  Authorization\User\PushSubscription\Application\Command\SubscribeToPushNotifications\SubscribeToPushNotificationsCommandHandler:
    class: Authorization\User\PushSubscription\Application\Command\SubscribeToPushNotifications\SubscribeToPushNotificationsCommandHandler
    arguments:
      $pushSubscriptionRepository: '@Authorization\User\PushSubscription\Domain\Model\PushSubscriptionRepository'
      $domainEventCollectorService: '@Shared\Shared\Shared\Domain\Service\DomainEventCollectorService'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Authorization\User\PushSubscription\Application\Command\UnsubscribeFromPushNotifications\UnsubscribeFromPushNotificationsCommandHandler:
    class: Authorization\User\PushSubscription\Application\Command\UnsubscribeFromPushNotifications\UnsubscribeFromPushNotificationsCommandHandler
    arguments:
      $pushSubscriptionRepository: '@Authorization\User\PushSubscription\Domain\Model\PushSubscriptionRepository'
      $domainEventCollectorService: '@Shared\Shared\Shared\Domain\Service\DomainEventCollectorService'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Authorization\User\PushSubscription\Application\Command\SendPushNotification\SendPushNotificationCommandHandler:
    class: Authorization\User\PushSubscription\Application\Command\SendPushNotification\SendPushNotificationCommandHandler
    arguments:
      $pushSubscriptionRepository: '@Authorization\User\PushSubscription\Domain\Model\PushSubscriptionRepository'
      $pushNotificationSender: '@Shared\Push\Push\Domain\Service\PushNotificationSender'
      $domainEventCollectorService: '@Shared\Shared\Shared\Domain\Service\DomainEventCollectorService'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
