services:
  Nutrition\Catalog\Category\Infrastructure\UI\API\Controller\GetCategoriesController:
    class: Nutrition\Catalog\Category\Infrastructure\UI\API\Controller\GetCategoriesController
    arguments:
      $messageBus: '@messenger.bus.default'
      $logger: '@logger'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Catalog\Category\Infrastructure\UI\API\Controller\GetCategoryController:
    class: Nutrition\Catalog\Category\Infrastructure\UI\API\Controller\GetCategoryController
    arguments:
      $messageBus: '@messenger.bus.default'
      $logger: '@logger'
    tags:
      - { name: controller.service_arguments }
