services:
  Integration\Mercadona\Infrastructure\Application\Console\SyncMercadonaCatalogCommand:
    class: Integration\Mercadona\Infrastructure\Application\Console\SyncMercadonaCatalogCommand
    arguments:
      $catalogProvider: '@Integration\Mercadona\Domain\Service\MercadonaCatalogProvider'
      $nutritionExtractor: '@Integration\Mercadona\Domain\Service\MercadonaNutritionExtractor'
      $importedRegistry: '@Integration\Mercadona\Domain\Service\ImportedProductRegistry'
      $importQueue: '@Integration\Mercadona\Domain\Service\MercadonaImportQueue'
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: 'console.command' }

  Integration\Mercadona\Infrastructure\Application\Console\BackfillMercadonaPricesCommand:
    class: Integration\Mercadona\Infrastructure\Application\Console\BackfillMercadonaPricesCommand
    arguments:
      $catalogProvider: '@Integration\Mercadona\Domain\Service\MercadonaCatalogProvider'
      $missingPriceRegistry: '@Integration\Mercadona\Domain\Service\MissingPriceRegistry'
      $priceQueue: '@integration.mercadona.price_queue'
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: 'console.command' }
