services:
  Economy\Finance\BalanceCheck\Application\Query\GetFinanceBalanceChecksQueryHandler:
    class: Economy\Finance\BalanceCheck\Application\Query\GetFinanceBalanceChecksQueryHandler
    arguments:
      $needleDataQuery: '@Economy\Finance\BalanceCheck\Domain\QueryModel\GetFinanceBalanceChecksNeedleDataQuery'
      $dataTransform: '@Economy\Finance\BalanceCheck\Application\Query\GetFinanceBalanceChecksDataTransform'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Economy\Finance\BalanceCheck\Application\Query\GetFinanceBalanceChecksDataTransform:
    class: Economy\Finance\BalanceCheck\Infrastructure\UI\API\DataTransform\ApiGetFinanceBalanceChecksDataTransform
