services:
  Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\GetArticlesController:
    class: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\GetArticlesController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\GetArticleController:
    class: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\GetArticleController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\CreateArticleController:
    class: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\CreateArticleController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\ImportGlobalArticleController:
    class: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\ImportGlobalArticleController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\UpdateArticleController:
    class: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\UpdateArticleController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\DeleteArticleController:
    class: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\DeleteArticleController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }
