get_articles:
  path: /api/v1/nutrition/catalog/articles
  methods: [GET]
  controller: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\GetArticlesController

get_article_facets:
  path: /api/v1/nutrition/catalog/article-facets
  methods: [GET]
  controller: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\GetArticleFacetsController

get_article:
  path: /api/v1/nutrition/catalog/article/{articleId}
  methods: [GET]
  controller: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\GetArticleController

create_article:
  path: /api/v1/nutrition/catalog/article
  methods: [POST]
  controller: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\CreateArticleController

import_global_article:
  path: /api/v1/nutrition/catalog/article/import/{globalArticleId}
  methods: [POST]
  controller: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\ImportGlobalArticleController

update_article:
  path: /api/v1/nutrition/catalog/article/{articleId}
  methods: [PUT]
  controller: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\UpdateArticleController

delete_article:
  path: /api/v1/nutrition/catalog/article/{articleId}
  methods: [DELETE]
  controller: Nutrition\Catalog\Article\Infrastructure\UI\API\Controller\DeleteArticleController
