services:
  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\StartProductionController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\StartProductionController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\CheckProductionItemController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\CheckProductionItemController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\UncookProductionItemController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\UncookProductionItemController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\DiscardProductionController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\DiscardProductionController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionsController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionsController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionProposalController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionProposalController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionItemController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionItemController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\CookProductionItemController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\CookProductionItemController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\AdjustProductionItemIngredientsController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\AdjustProductionItemIngredientsController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\RestoreProductionItemIngredientsController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\RestoreProductionItemIngredientsController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\LabelProductionItemController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\LabelProductionItemController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetRecipeLotsController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetRecipeLotsController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\ServeProductionItemSubRecipeController:
    class: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\ServeProductionItemSubRecipeController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }
