get_production_proposal:
  path: /api/v1/nutrition/kitchen/proposal
  methods: [GET]
  controller: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionProposalController

start_production:
  path: /api/v1/nutrition/kitchen/productions
  methods: [POST]
  controller: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\StartProductionController

get_productions:
  path: /api/v1/nutrition/kitchen/productions
  methods: [GET]
  controller: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionsController

cook_production_item:
  path: /api/v1/nutrition/kitchen/productions/{productionId}/items/{itemId}/cook
  methods: [PUT]
  controller: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\CookProductionItemController

check_production_item:
  path: /api/v1/nutrition/kitchen/productions/{productionId}/items/{itemId}/checks
  methods: [PUT]
  controller: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\CheckProductionItemController

uncook_production_item:
  path: /api/v1/nutrition/kitchen/productions/{productionId}/items/{itemId}/uncook
  methods: [PUT]
  controller: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\UncookProductionItemController

get_production_item:
  path: /api/v1/nutrition/kitchen/productions/{productionId}/items/{itemId}
  methods: [GET]
  controller: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionItemController

get_production:
  path: /api/v1/nutrition/kitchen/productions/{productionId}
  methods: [GET]
  controller: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\GetProductionController

discard_production:
  path: /api/v1/nutrition/kitchen/productions/{productionId}
  methods: [DELETE]
  controller: Nutrition\Kitchen\Production\Infrastructure\UI\API\Controller\DiscardProductionController
