services:
  Gym\Analytics\Stats\Infrastructure\UI\API\Controller\GetGymStatsController:
    class: Gym\Analytics\Stats\Infrastructure\UI\API\Controller\GetGymStatsController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Gym\Analytics\Stats\Infrastructure\UI\API\Controller\GetExerciseStatsController:
    class: Gym\Analytics\Stats\Infrastructure\UI\API\Controller\GetExerciseStatsController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }
