services:
  Economy\Finance\Recurrence\Application\Command\CreateFinanceRecurrenceCommandHandler:
    class: Economy\Finance\Recurrence\Application\Command\CreateFinanceRecurrenceCommandHandler
    arguments:
      $financeRecurrenceRepository: '@Economy\Finance\Recurrence\Domain\Model\FinanceRecurrenceRepository'
      $needleDataQuery: '@Economy\Finance\Recurrence\Domain\QueryModel\CreateFinanceRecurrenceNeedleDataQuery'
      $domainEventCollectorService: '@Shared\Shared\Shared\Domain\Service\DomainEventCollectorService'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Economy\Finance\Recurrence\Application\Command\UpdateFinanceRecurrenceCommandHandler:
    class: Economy\Finance\Recurrence\Application\Command\UpdateFinanceRecurrenceCommandHandler
    arguments:
      $financeRecurrenceRepository: '@Economy\Finance\Recurrence\Domain\Model\FinanceRecurrenceRepository'
      $needleDataQuery: '@Economy\Finance\Recurrence\Domain\QueryModel\UpdateFinanceRecurrenceNeedleDataQuery'
      $domainEventCollectorService: '@Shared\Shared\Shared\Domain\Service\DomainEventCollectorService'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Economy\Finance\Recurrence\Application\Command\DeleteFinanceRecurrenceCommandHandler:
    class: Economy\Finance\Recurrence\Application\Command\DeleteFinanceRecurrenceCommandHandler
    arguments:
      $financeRecurrenceRepository: '@Economy\Finance\Recurrence\Domain\Model\FinanceRecurrenceRepository'
      $domainEventCollectorService: '@Shared\Shared\Shared\Domain\Service\DomainEventCollectorService'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Economy\Finance\Recurrence\Application\Command\DeleteFinanceRecurrencesByAccountCommandHandler:
    class: Economy\Finance\Recurrence\Application\Command\DeleteFinanceRecurrencesByAccountCommandHandler
    arguments:
      $financeRecurrenceRepository: '@Economy\Finance\Recurrence\Domain\Model\FinanceRecurrenceRepository'
      $domainEventCollectorService: '@Shared\Shared\Shared\Domain\Service\DomainEventCollectorService'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }

  Economy\Finance\Recurrence\Application\Command\GenerateFinanceRecurrenceCommandHandler:
    class: Economy\Finance\Recurrence\Application\Command\GenerateFinanceRecurrenceCommandHandler
    arguments:
      $financeRecurrenceRepository: '@Economy\Finance\Recurrence\Domain\Model\FinanceRecurrenceRepository'
      $domainEventCollectorService: '@Shared\Shared\Shared\Domain\Service\DomainEventCollectorService'
      $dateTimeGenerator: '@Shared\Tool\Tool\Domain\Service\DateTimeGenerator'
    tags:
      - { name: 'messenger.message_handler', bus: 'messenger.bus.default' }
