services:
  Economy\Finance\Recurrence\Application\Subscriber\DeleteFinanceRecurrencesOnFinanceAccountDeleted:
    class: Economy\Finance\Recurrence\Application\Subscriber\DeleteFinanceRecurrencesOnFinanceAccountDeleted
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: 'domain_event_subscriber', event: 'golifecraft.economy.event.1.finance_account.deleted' }
