services:
  Economy\Finance\Account\Domain\Model\FinanceAccountRepository:
    class: Economy\Finance\Account\Infrastructure\Domain\Model\Doctrine\DoctrineFinanceAccountRepository
    factory: ["@doctrine.orm.tenant_manager_entity_manager", getRepository]
    arguments:
      - Economy\Finance\Account\Domain\Model\FinanceAccount
