services:
  Authorization\User\User\Infrastructure\UI\API\Controller\GetUsersController:
    class: Authorization\User\User\Infrastructure\UI\API\Controller\GetUsersController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Authorization\User\User\Infrastructure\UI\API\Controller\UpdateMyProfileController:
    class: Authorization\User\User\Infrastructure\UI\API\Controller\UpdateMyProfileController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Authorization\User\User\Infrastructure\UI\API\Controller\ChangeMyPasswordController:
    class: Authorization\User\User\Infrastructure\UI\API\Controller\ChangeMyPasswordController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Authorization\User\User\Infrastructure\UI\API\Controller\GetMyProfileController:
    class: Authorization\User\User\Infrastructure\UI\API\Controller\GetMyProfileController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }

  Authorization\User\User\Infrastructure\UI\API\Controller\ChangeMyThemeController:
    class: Authorization\User\User\Infrastructure\UI\API\Controller\ChangeMyThemeController
    arguments:
      $messageBus: '@messenger.bus.default'
    tags:
      - { name: controller.service_arguments }
