services:
  Nutrition\Catalog\Article\Domain\QueryModel\GetArticlesNeedleDataQuery:
    class: Nutrition\Catalog\Article\Infrastructure\Domain\QueryModel\Doctrine\DoctrineGetArticlesNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'

  Nutrition\Catalog\Article\Domain\QueryModel\GetArticleNeedleDataQuery:
    class: Nutrition\Catalog\Article\Infrastructure\Domain\QueryModel\Doctrine\DoctrineGetArticleNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'

  Nutrition\Catalog\Article\Domain\QueryModel\GetArticleFacetsNeedleDataQuery:
    class: Nutrition\Catalog\Article\Infrastructure\Domain\QueryModel\Doctrine\DoctrineGetArticleFacetsNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'

  Nutrition\Catalog\Article\Domain\QueryModel\CreateArticleNeedleDataQuery:
    class: Nutrition\Catalog\Article\Infrastructure\Domain\QueryModel\Doctrine\DoctrineCreateArticleNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'

  Nutrition\Catalog\Article\Domain\QueryModel\UpdateArticleNeedleDataQuery:
    class: Nutrition\Catalog\Article\Infrastructure\Domain\QueryModel\Doctrine\DoctrineUpdateArticleNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'
