services:
  Nutrition\Diary\Diary\Infrastructure\Domain\QueryModel\Doctrine\DiaryReaderRecipeNutritionGraphProvider:
    class: Nutrition\Recipe\Recipe\Infrastructure\Domain\QueryModel\Doctrine\DoctrineRecipeNutritionGraphProvider
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'

  Nutrition\Diary\Diary\Domain\QueryModel\GetDiaryNeedleDataQuery:
    class: Nutrition\Diary\Diary\Infrastructure\Domain\QueryModel\Doctrine\DoctrineGetDiaryNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'
      $graphProvider: '@Nutrition\Diary\Diary\Infrastructure\Domain\QueryModel\Doctrine\DiaryReaderRecipeNutritionGraphProvider'
      $breakdownCalculator: '@Nutrition\Recipe\Recipe\Domain\Service\RecipeBreakdownCalculator'

  Nutrition\Diary\Diary\Domain\QueryModel\GetDiaryCalendarNeedleDataQuery:
    class: Nutrition\Diary\Diary\Infrastructure\Domain\QueryModel\Doctrine\DoctrineGetDiaryCalendarNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'

  Nutrition\Diary\Diary\Domain\QueryModel\FindArticleDiaryReactionNeedleDataQuery:
    class: Nutrition\Diary\Diary\Infrastructure\Domain\QueryModel\Doctrine\DoctrineFindArticleDiaryReactionNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'

  Nutrition\Diary\Diary\Domain\QueryModel\FindDiaryEntriesByDateNeedleDataQuery:
    class: Nutrition\Diary\Diary\Infrastructure\Domain\QueryModel\Doctrine\DoctrineFindDiaryEntriesByDateNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.writer_tenant_connection'

  Nutrition\Diary\Diary\Domain\QueryModel\FindImpactedDiaryEntriesNeedleDataQuery:
    class: Nutrition\Diary\Diary\Infrastructure\Domain\QueryModel\Doctrine\DoctrineFindImpactedDiaryEntriesNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.writer_tenant_connection'
      $graphProvider: '@Nutrition\Diary\Diary\Infrastructure\Domain\Service\DiaryWriterRecipeNutritionGraphProvider'
      $calculator: '@Nutrition\Recipe\Recipe\Domain\Service\RecipeNutritionCalculator'

  Nutrition\Diary\Diary\Domain\QueryModel\GetDiaryShoppingNeedsNeedleDataQuery:
    class: Nutrition\Diary\Diary\Infrastructure\Domain\QueryModel\Doctrine\DoctrineGetDiaryShoppingNeedsNeedleDataQuery
    arguments:
      $connection: '@doctrine.dbal.reader_tenant_connection'
      $graphProvider: '@Nutrition\Diary\Diary\Infrastructure\Domain\QueryModel\Doctrine\DiaryReaderRecipeNutritionGraphProvider'
      $needsCalculator: '@Nutrition\Diary\Diary\Domain\Service\DiaryArticleNeedsCalculator'
